#!/usr/bin/env bash
# scripts/fdc-log.sh
# fdc-version: 2026.09.14
#
# OPTIONAL. Regenerates fdc/log.md — a newest-first, date-grouped history of
# every commit that touched the /fdc/ knowledge layer (OKF "log.md" idea).
# Git already has this history; the point is that an agent reading fdc/ sees
# "what changed recently" without running git. It is generated, never
# hand-edited, and never part of the pre-commit hook. Commit the result if you
# want it shared (a doc-only change, so the drift checker is happy).
#
# Usage:   bash scripts/fdc-log.sh            # writes fdc/log.md
#          FDC_LOG_MAX=200 bash scripts/fdc-log.sh
#
# Portable: stock macOS /bin/bash 3.2 and Linux.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
# --- per-repo settings (scripts/fdc.conf overrides the defaults above) -------
fdc_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
# shellcheck disable=SC1090
[[ -f "$fdc_root/scripts/fdc.conf" ]] && . "$fdc_root/scripts/fdc.conf"
[[ -d fdc ]] || { echo "[fdc-log] no fdc/ — nothing to log."; exit 0; }
git rev-parse --verify -q HEAD >/dev/null 2>&1 || { echo "[fdc-log] no commits yet."; exit 0; }
max="${FDC_LOG_MAX:-500}"
out=fdc/log.md

{
    echo "# fdc update log"
    echo
    echo "<!-- Generated by scripts/fdc-log.sh from git history. Do not edit; re-run the script. -->"
    echo
    git log -n "$max" --date=short --format='%x01%ad%x09%h%x09%s' --name-only -- fdc/ \
    | awk -F'\t' '
        function flush() {
            if (subj == "" || files == "") { subj = ""; files = ""; return }
            if (date != last) { if (last != "") print ""; print "## " date; print ""; last = date }
            print "* **" subj "** (`" hash "`): " files
            subj = ""; files = ""
        }
        substr($0, 1, 1) == "\001" { flush(); h = substr($0, 2); n = split(h, p, "\t"); date = p[1]; hash = p[2]; subj = p[3]; for (i = 4; i <= n; i++) subj = subj "\t" p[i]; next }
        /^$/ { next }
        { if ($0 != "fdc/log.md") files = files (files == "" ? "" : ", ") "`" $0 "`" }
        END { flush() }
    '
} > "$out.tmp"
mv "$out.tmp" "$out"
echo "[fdc-log] wrote $out ($(grep -c '^\* ' "$out" | tr -d ' ') entries)."
